import Footer from "./Components/Navigation/Footer";
import NavigationBar from "./Components/Navigation/NavigationBar";
import "./globals.css";
import { Rubik } from "next/font/google";

const font = Rubik({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <NavigationBar />
        <div className="pt-[166px] max-w-[2520px] mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
